name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    environment: production
    env:
      PLASMO_PUBLIC_PEXELS_API_KEY: ${{ secrets.PLASMO_PUBLIC_PEXELS_API_KEY }}
      PLASMO_PUBLIC_UNSPLASH_ACCESS_KEY: ${{ secrets.PLASMO_PUBLIC_UNSPLASH_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 18.12
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.12
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm package
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3.8.0
        with:
          keys: ${{ secrets.BPP_KEYS }}
          artifact: build/chrome-mv3-prod.zip
